version: '3.8'
services:
  sosmeddb:
    image: postgres:15
    container_name: sosmeddb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: sosmed
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - sosmed
  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./Dockerfile
    container_name: auth-service
    environment:
      - GO_ENV=development
      - HTTP_PORT=auth-service:8080
      - GRPC_PORT=auth-service:50051
      - ACCOUNT_SERVICE_URL=account-service:50052
      - DB_HOST=sosmeddb
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=authdb
      - DB_SSLMODE=disable
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - '8080:8080'
      - '50051:50051'
    depends_on:
      - sosmeddb
      - account-service
    networks:
      - sosmed
    restart: on-failure
  account-service:
    build:
      context: ./account-service
      dockerfile: ./Dockerfile
    container_name: account-service
    environment:
      - GO_ENV=development
      - HTTP_PORT=account-service:8081
      - GRPC_PORT=account-service:50052
      - DB_HOST=sosmeddb
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=accountdb
      - DB_SSLMODE=disable
    ports:
      - '8082:8082'
      - '50052:50052'
    depends_on:
      - sosmeddb
    networks:
      - sosmed
    restart: on-failure

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    ports:
      - 9200:9200
    networks:
      - sosmed
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - sosmed

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
    networks:
      - sosmed
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - sosmed

volumes:
  db-data:
  esdata:
networks:
  sosmed:
    driver: bridge
