// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.9
// source: search/search.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SearchService_SearchUserByUsername_FullMethodName = "/search.SearchService/SearchUserByUsername"
	SearchService_SearchAllUsers_FullMethodName       = "/search.SearchService/SearchAllUsers"
)

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	SearchUserByUsername(ctx context.Context, in *SearchUserByUsernameRequest, opts ...grpc.CallOption) (*SearchUserByUsernameResponse, error)
	SearchAllUsers(ctx context.Context, in *SearchAllUsersRequest, opts ...grpc.CallOption) (*SearchAllUsersResponse, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchUserByUsername(ctx context.Context, in *SearchUserByUsernameRequest, opts ...grpc.CallOption) (*SearchUserByUsernameResponse, error) {
	out := new(SearchUserByUsernameResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchUserByUsername_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) SearchAllUsers(ctx context.Context, in *SearchAllUsersRequest, opts ...grpc.CallOption) (*SearchAllUsersResponse, error) {
	out := new(SearchAllUsersResponse)
	err := c.cc.Invoke(ctx, SearchService_SearchAllUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations should embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	SearchUserByUsername(context.Context, *SearchUserByUsernameRequest) (*SearchUserByUsernameResponse, error)
	SearchAllUsers(context.Context, *SearchAllUsersRequest) (*SearchAllUsersResponse, error)
}

// UnimplementedSearchServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchUserByUsername(context.Context, *SearchUserByUsernameRequest) (*SearchUserByUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchUserByUsername not implemented")
}
func (UnimplementedSearchServiceServer) SearchAllUsers(context.Context, *SearchAllUsersRequest) (*SearchAllUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchAllUsers not implemented")
}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchUserByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUserByUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchUserByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchUserByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchUserByUsername(ctx, req.(*SearchUserByUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_SearchAllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).SearchAllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchService_SearchAllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).SearchAllUsers(ctx, req.(*SearchAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "search.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchUserByUsername",
			Handler:    _SearchService_SearchUserByUsername_Handler,
		},
		{
			MethodName: "SearchAllUsers",
			Handler:    _SearchService_SearchAllUsers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "search/search.proto",
}
